export const COM_SHOW_SIDE_BAR = 'COM_SHOW_SIDE_BAR'// 侧边栏
export const COM_SAVE_SEARCH_HISTORY = 'COM_SAVE_SEARCH_HISTORY'// 保存历史搜索
export const COM_DELETE_SEARCH_HISTORY = 'COM_DELETE_SEARCH_HISTORY'// 删除历史搜索
export const COM_CLEAR_HISTORY_ALL = 'COM_CLEAR_HISTORY_ALL'